### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by joshim5** [EthanMacdonald/SubredditSimulator#1]
Hi Ethan,

Found your post on Reddit - super cool! I'm an undergrad and would love to take a look at your results. Unfortunately, your paper is no longer accessible here: https://ethanmacdonald.github.io/wp/wp-content/uploads/2015/03/Comp_599__Final_Project.pdf

Could you repost it or send it to me? Awesome work!

Thanks,
Josh

**Comment by EthanMacdonald** [comment]
Sorry for the delay on this, here you go!
 
[Comp_599_Final_Project.pdf](https://github.com/EthanMacdonald/SubredditSimulator/files/679942/Comp_599_Final_Project.pdf)

Also, if you haven't already seen it, this blog post is excellent: http://karpathy.github.io/2015/05/21/rnn-effectiveness/

For this project I basically hacked away on Karpathy's repo, since RNNs were still pretty new to me :)
